trigger:
  batch: true
  branches:
    include: 
      - dev
      - beta
      - master

pool:
  vmImage: windows-latest

steps:
- script: del /f $(System.DefaultWorkingDirectory)\.env
  displayName: delete .env file

- script: ren $(System.DefaultWorkingDirectory)\.env.dev .env
  displayName: copy dev environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')

- script: ren $(System.DefaultWorkingDirectory)\.env.staging .env
  displayName: copy beta environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/beta')

- script: ren $(System.DefaultWorkingDirectory)\.env.prod .env
  displayName: copy production environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: npm install

- script: npm run build
  displayName: npm build dev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')

- script: npm run build
  displayName: npm build beta
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/beta')

- script: npm run build
  displayName: npm build production
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/build
    artifactName: '$(Build.DefinitionName).$(Build.BuildNumber)'
    publishLocation: 'Container'
  displayName: 'publish build artifacts'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)\build\**'
    azureSubscription: 'cv-card-dev-rg'
    Destination: 'AzureBlob'
    storage: 'a360cvcarddev'
    ContainerName: '$web'
  displayName: 'publish to dev'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

- task: AzureCLI@2
  inputs:
    azureSubscription: 'aquila360-rg-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge --resource-group Aquila360 --profile aquila360 --name cv-card-admin-dev --content-paths "/*"'
  displayName: 'purge dev cdn'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)\build\**'
    azureSubscription: 'cv-card-beta-rg'
    Destination: 'AzureBlob'
    storage: 'a360cvcardadminbeta'
    ContainerName: '$web'
  displayName: 'publish to beta'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/beta')

- task: AzureCLI@2
  inputs:
    azureSubscription: 'aquila360-rg-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge --resource-group Aquila360 --profile aquila360 --name cv-card-admin-beta --content-paths "/*"'
  displayName: 'purge beta cdn'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/beta')